apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflow-api
  namespace: nextflow
  labels:
    app: nextflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextflow-api
  template:
    metadata:
      labels:
        app: nextflow-api
    spec:
      serviceAccountName: nextflow-api
      containers:
        - name: nextflow-api
          image: ghcr.io/example/nextflow-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: NEXTFLOW_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REDIS_URL
              value: "redis://redis:6379/0"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: nextflow-config
              mountPath: /opt/nextflow
      volumes:
        - name: nextflow-config
          configMap:
            name: nextflow-config
