apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-api
  namespace: nextflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-runner
  namespace: nextflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-api
  namespace: nextflow
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-api
  namespace: nextflow
subjects:
  - kind: ServiceAccount
    name: nextflow-api
    namespace: nextflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-api
