apiVersion: v1
kind: Service
metadata:
  name: nextflow-k8s-service
  namespace: nextflow
  labels:
    app: nextflow-k8s-service
spec:
  type: ClusterIP
  selector:
    app: nextflow-k8s-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
